import os
from fpdf import FPDF
from flask import current_app
from app.module2.models import Scan, User, Defect

class ComplianceReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 16)
        self.cell(0, 10, 'Defect Liability Period (DLP) Compliance Report', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.cell(0, 10, 'Generated by DLP-Advisor System', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}}', 0, 0, 'C')

def generate_pdf(scan_id):
    scan = Scan.query.get(scan_id)
    if not scan:
        return None
        
    user = User.query.get(scan.user_id) if scan.user_id else None
    defects = Defect.query.filter_by(scan_id=scan.id).all()
    
    pdf = ComplianceReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # Section 1: Property & Owner Details
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '1. PROPERTY & OWNERSHIP DETAILS', 0, 1)
    pdf.set_font('Arial', '', 10)
    
    col_width = 90
    line_height = 6
    
    # Row 1
    pdf.cell(col_width, line_height, f"Owner Name: {user.full_name if user else 'N/A'}", 0)
    pdf.cell(col_width, line_height, f"IC Number: {user.ic_number if user else 'N/A'}", 0, 1)
    
    # Row 2
    pdf.cell(col_width, line_height, f"Phone: {user.phone_number if user else 'N/A'}", 0)
    pdf.cell(col_width, line_height, f"Project: {scan.name.split('-')[0] if scan.name else 'N/A'}", 0, 1)
    
    # Row 3
    pdf.cell(col_width, line_height, f"Unit No: {scan.name.split('-')[-1].strip() if '-' in scan.name else 'N/A'}", 0)
    pdf.cell(col_width, line_height, f"Parcel No: {scan.parcel_number or 'N/A'}", 0, 1)
    
    # Row 4
    pdf.cell(col_width, line_height, f"Grant No: {scan.grant_number or 'N/A'}", 0)
    pdf.cell(col_width, line_height, f"Bank: {scan.bank_name or 'N/A'}", 0, 1)
    
    # Row 5
    vp = scan.vp_date.strftime('%d/%m/%Y') if scan.vp_date else 'N/A'
    ccc = scan.ccc_date.strftime('%d/%m/%Y') if scan.ccc_date else 'N/A'
    pdf.cell(col_width, line_height, f"VP Date: {vp}", 0)
    pdf.cell(col_width, line_height, f"CCC Date: {ccc}", 0, 1)
    
    pdf.ln(5)
    
    # Section 2: Defect List
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '2. SCHEDULE OF DEFECTS', 0, 1)
    
    pdf.set_fill_color(200, 220, 255)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(15, 10, '#', 1, 0, 'C', 1)
    pdf.cell(40, 10, 'Location', 1, 0, 'C', 1)
    pdf.cell(90, 10, 'Description', 1, 0, 'C', 1)
    pdf.cell(45, 10, 'Status', 1, 1, 'C', 1)
    
    pdf.set_font('Arial', '', 10)
    
    for i, defect in enumerate(defects, 1):
        # Calculate height needed
        desc = defect.description or ''
        # Simple estimate for multi-line
        pdf.cell(15, 10, str(i), 1, 0, 'C')
        pdf.cell(40, 10, defect.location or 'General', 1, 0)
        pdf.cell(90, 10, desc[:50] + ('...' if len(desc)>50 else ''), 1, 0)
        pdf.cell(45, 10, defect.status, 1, 1, 'C')
        
    pdf.ln(10)
    
    # Section 3: Signatures
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, '3. ACKNOWLEDGEMENT', 0, 1)
    
    pdf.set_font('Arial', '', 10)
    pdf.ln(15)
    
    y = pdf.get_y()
    pdf.line(10, y, 90, y)
    pdf.line(110, y, 190, y)
    
    pdf.cell(90, 5, "Homeowner Signature", 0, 0, 'C')
    pdf.cell(10, 5, "", 0, 0)
    pdf.cell(90, 5, "Developer Representative", 0, 1, 'C')
    
    pdf.cell(90, 5, f"Date: {vp}", 0, 0, 'C') # Using VP as placeholder or today
    pdf.cell(10, 5, "", 0, 0)
    pdf.cell(90, 5, "Date: _______________", 0, 1, 'C')

    # Output
    reports_dir = os.path.join(current_app.root_path, 'static', 'reports')
    os.makedirs(reports_dir, exist_ok=True)
    
    filename = f"DLP_Report_{scan.id}.pdf"
    filepath = os.path.join(reports_dir, filename)
    
    pdf.output(filepath)
    return filename
